// 多站点预构建：把 shared/ 里的共用模板按各站 site.json 渲染到站点目录，生成联系客服页，复制共用图片与 CMS 后台。
// 用法：node tools/prebuild.mjs <site-id>      （site-id = sites/ 下的目录名，如 sub2api、newapi）
// 规则：
//   - shared/pages/**/*.md 里的 %%KEY%% 用 site.json 顶层字段替换（BASE_URL、MODELS_URL、KEYS_URL、SITE_NAME、SITE_URL…）
//   - 站点若在 overrides/ 下有同路径文件，则用站点自己的版本，不用共用模板
//   - 生成的文件都带 <!-- generated --> 标记并被 .gitignore 忽略，改内容请改 shared/ 或 overrides/
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const siteId = process.argv[2]
if (!siteId) { console.error('usage: node tools/prebuild.mjs <site-id>'); process.exit(1) }
const SITE = path.join(ROOT, siteId)
const SHARED = path.join(ROOT, 'shared')
const site = JSON.parse(fs.readFileSync(path.join(SITE, 'site.json'), 'utf8'))

const vars = {
  SITE_NAME: site.name, SITE_URL: site.site_url, BASE_URL: site.base_url, MODELS_URL: site.models_url,
  KEYS_URL: site.keys_url, CONSOLE_URL: site.console_url, DOCS_URL: `https://${site.domain}`,
  KEY_WORD: site.key_word || 'API 密钥', HOURS: site.contact?.hours || '',
}
const render = (s) => s.replace(/%%([A-Z_]+)%%/g, (m, k) => (k in vars ? vars[k] : m))
const walk = (dir, base = dir) => fs.existsSync(dir)
  ? fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => e.isDirectory() ? walk(path.join(dir, e.name), base) : [path.relative(base, path.join(dir, e.name))])
  : []
const write = (rel, content) => {
  const p = path.join(SITE, rel)
  fs.mkdirSync(path.dirname(p), { recursive: true })
  fs.writeFileSync(p, content)
}
const GEN = '<!-- generated by tools/prebuild.mjs — 改内容请改 shared/pages 或本站 overrides/，此文件会被覆盖 -->\n'

// 1) 共用页面
let n = 0
for (const rel of walk(path.join(SHARED, 'pages'))) {
  if (!rel.endsWith('.md')) continue
  const override = path.join(SITE, 'overrides', rel)
  const src = fs.existsSync(override) ? fs.readFileSync(override, 'utf8') : render(fs.readFileSync(path.join(SHARED, 'pages', rel), 'utf8'))
  const left = src.match(/%%[A-Z_]+%%/g)
  if (left) throw new Error(`${rel}: 未替换的占位符 ${[...new Set(left)]}`)
  // frontmatter 必须在文件最前面，标记放在 frontmatter 之后
  const out = src.startsWith('---') ? src.replace(/^---\n[\s\S]*?\n---\n/, (fm) => fm + GEN) : GEN + src
  write(rel, out); n++
}
// 站点自己的 overrides 里不属于共用模板的页面也一并复制（站点专属页放 overrides 便于和生成物同目录）
for (const rel of walk(path.join(SITE, 'overrides'))) {
  if (!rel.endsWith('.md') || fs.existsSync(path.join(SHARED, 'pages', rel))) continue
  write(rel, GEN + fs.readFileSync(path.join(SITE, 'overrides', rel), 'utf8')); n++
}

// 2) 联系客服页（由 site.json 生成）
const c = site.contact || {}
const wx = c.wecom_url ? `
<div class="card">
<img class="qr" src="${c.wecom_qr}" alt="企业微信客服二维码">
<h3>企业微信在线客服</h3>
<p>微信「扫一扫」即可对话</p>
<a class="btn wx" href="${c.wecom_url}" target="_blank" rel="noopener noreferrer">打开微信客服</a>
<div class="hint">电脑上会唤起微信客户端，手机上直接进入对话</div>
</div>` : ''
const tg = c.telegram_url ? `
<div class="card">
<img class="qr" src="${c.telegram_qr}" alt="Telegram 频道二维码">
<h3>Telegram 订阅频道</h3>
<p>服务状态 · 公告 · 上新通知</p>
<a class="btn tg" href="${c.telegram_url}" target="_blank" rel="noopener noreferrer">加入频道</a>
<div class="hint">非即时客服，仅用于接收通知</div>
</div>` : ''
write('contact.md', `---
title: 联系客服
outline: false
---
${GEN}
# 联系客服

<div class="xm-contact">
<p><span class="chip">工作时间 ${c.hours || ''}</span></p>
<div class="grid">${wx}${tg}
</div>
</div>

## 联系时请一并提供，处理更快

- 注册邮箱
- 充值 / 兑换问题：订单号或兑换码
- 调用报错：完整报错文案、使用的模型、大致时间

::: tip 先自助排查
常见问题多数可以在 [错误码对照](/errors) 和 [常见问题](/faq) 里直接解决。
:::
`)

// 3) 共用图片、CMS 后台
// 不用 fs.cpSync：Node 24 在 Windows 中文路径下会崩溃（0xC0000409），手动递归复制
const copyDir = (from, to) => {
  if (!fs.existsSync(from)) return 0
  let count = 0
  for (const rel of walk(from)) {
    const dst = path.join(to, rel)
    fs.mkdirSync(path.dirname(dst), { recursive: true })
    fs.copyFileSync(path.join(from, rel), dst)
    count++
  }
  return count
}
const imgs = copyDir(path.join(SHARED, 'img'), path.join(SITE, 'public', 'img', 'shared'))
const adm = copyDir(path.join(SHARED, 'admin'), path.join(SITE, 'public', 'admin'))

console.log(`[prebuild ${siteId}] pages=${n} contact=1 sharedImgs=${imgs} admin=${adm} base=${site.base_url}`)
