// Generate only site-scoped static files. Never delete source files, run a shell, or deploy.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { stageCourse } from './course-bridge.mjs'
import { createRequire } from 'node:module'
const require=createRequire(import.meta.url)
require('./vendor/qr-local.cjs')
export const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
export const GEN='<!-- generated by tools/prebuild.mjs; edit shared/pages or site overrides -->\n'
export function render(text,vars){
 const result=text.replace(/%%([A-Z_]+)%%/g,(token,key)=>Object.hasOwn(vars,key)?String(vars[key]):token)
 const missing=result.match(/%%[A-Z_]+%%/g)
 if(missing)throw Error('Unresolved variables: '+[...new Set(missing)].join(', '))
 return result
}
export function markGenerated(text){
 const normalized=text.replace(/^\uFEFF/,'').replace(/\r\n/g,'\n')
 if(!normalized.startsWith('---\n'))return GEN+normalized
 const fm=normalized.match(/^---\n[\s\S]*?\n---(?:\n|$)/)
 if(!fm)throw Error('Invalid frontmatter')
 return fm[0].trimEnd()+'\n'+GEN+normalized.slice(fm[0].length)
}
function files(dir,base=dir){
 if(!fs.existsSync(dir))return []
 return fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry=>{
  if(entry.isSymbolicLink())throw Error('Symlinks are not supported: '+entry.name)
  const full=path.join(dir,entry.name)
  return entry.isDirectory()?files(full,base):[path.relative(base,full)]
 })
}
export function https(value,label){
 const url=new URL(value)
 if(url.protocol!=='https:'||url.username||url.password)throw Error(label+': expected HTTPS URL without credentials')
 return url.href
}
export function qrSVG(value){
 const modules=globalThis.XMQR.matrix(https(value,'Customer support')),size=modules.length+8
 let shape=''
 modules.forEach((row,y)=>row.forEach((dark,x)=>{if(dark)shape+=`M${x+4} ${y+4}h1v1h-1z`}))
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" shape-rendering="crispEdges"><rect width="${size}" height="${size}" fill="white"/><path fill="black" d="${shape}"/></svg>`
}
export function build(id,root=ROOT){
 if(!['sub2api','newapi'].includes(id))throw Error('Choose sub2api or newapi')
 const directory=path.join(root,id),shared=path.join(root,'shared')
 const site=JSON.parse(fs.readFileSync(path.join(directory,'site.json'),'utf8'))
 if(site.id!==id)throw Error('Site ID mismatch')
 for(const key of ['site_url','base_url','keys_url','models_url','console_url'])https(site[key],key)
 if(!/^[a-zA-Z0-9.-]+$/.test(site.domain))throw Error('Invalid documentation hostname')
 const other=id==='sub2api'?'xm.solov.cc':'api.solov.cc'
 for(const key of ['site_url','base_url','codex_base_url','openclaw_base_url','keys_url','models_url','console_url'])if(site[key]&&new URL(site[key]).hostname===other)throw Error('Cross-site URL: '+key)
 if(site.domain===(id==='sub2api'?'docs-new.solov.cc':'docs-sub.solov.cc'))throw Error('Cross-site docs hostname')
 for(const item of Object.values(site.downloads||{})){
  if(item.url)https(item.url,'Download URL')
  if(item.notes_url)https(item.notes_url,'Release notes URL')
  if(item.checksum&&!/^[a-f0-9]{64}$/i.test(item.checksum))throw Error('Invalid SHA-256')
 }
 const course=stageCourse(path.dirname(root))
 const origin=new URL(site.base_url).origin
 const vars={SITE_NAME:site.name,SITE_URL:site.site_url,BASE_URL:site.base_url,CODEX_BASE_URL:site.codex_base_url||site.base_url,OPENCLAW_BASE_URL:site.openclaw_base_url||origin+'/v1',KEYS_URL:site.keys_url,MODELS_URL:site.models_url,CONSOLE_URL:site.console_url,DOCS_URL:'https://'+site.domain,KEY_WORD:site.key_word||'API 密钥',HOURS:site.contact?.hours||''}
 https(vars.CODEX_BASE_URL,'Codex base URL')
 https(vars.OPENCLAW_BASE_URL,'OpenClaw base URL')
 const outputs=[]
 const pageRoot=path.join(shared,'pages'),overrideRoot=path.join(directory,'overrides')
 const pageNames=new Set([...files(pageRoot),...files(overrideRoot)].filter(name=>name.endsWith('.md')))
 for(const name of pageNames){
  const custom=path.join(overrideRoot,name),source=fs.existsSync(custom)?custom:path.join(pageRoot,name)
  outputs.push([name,markGenerated(render(fs.readFileSync(source,'utf8'),vars))])
 }
 outputs.push(...course.pages.map(([name,body])=>[name,markGenerated(body)]))
 const contact={...site.contact}
 if(contact.wecom_url&&contact.qr_mode!=='upload'){
  contact.wecom_qr='/img/contact/wecom-auto.svg'
  outputs.push(['public/img/contact/wecom-auto.svg',qrSVG(contact.wecom_url)])
 }
 outputs.push(['contact.md',markGenerated('---\ntitle: 联系客服\noutline: false\n---\n# 联系客服\n\n<SupportCard />\n\n## 求助前准备\n\n提供工具与系统版本、模型 ID、大致时间、脱敏错误文案和请求 ID。账户或订单问题仅在确认的客服会话中提供必要资料。\n\n不要发送 API Key、Authorization、Cookie、密码、验证码、未使用兑换码或整包原始配置。\n\n[排错顺序](/guide/troubleshooting) · [常见问题](/faq) · [错误码](/errors)\n')])
 const sourceNav=JSON.parse(fs.readFileSync(path.join(directory,'nav.json'),'utf8'))
 const courseNav={text:'Codex 零基础课程',items:[{text:'完整课程目录',link:'/learn/codex/'},...course.sidebar,{text:'第一次任务练习',link:'/learn/first-task'},{text:'文件夹练习',link:'/learn/working-with-files'},{text:'检查结果与修改',link:'/learn/review-and-revise'}]}
 const nav={nav:sourceNav.nav,sidebar:[sourceNav.sidebar[0],courseNav,...sourceNav.sidebar.slice(1)]}
 const publicSite={id:site.id,name:site.name,title:site.title,description:site.description,domain:site.domain,site_url:site.site_url,base_url:site.base_url,codex_base_url:vars.CODEX_BASE_URL,openclaw_base_url:vars.OPENCLAW_BASE_URL,contact,downloads:site.downloads||{}}
 outputs.push(['site.generated.json',JSON.stringify(publicSite,null,2)],['nav.generated.json',JSON.stringify(nav,null,2)],['course-provenance.generated.json',JSON.stringify({version:course.version,sources:course.sources},null,2)])
 const parent=new URL(site.site_url).origin
 outputs.push(['public/_headers',`/*\n  Content-Security-Policy: frame-ancestors 'self' ${parent}\n  Referrer-Policy: no-referrer\n  X-Content-Type-Options: nosniff\n`])
 const outputPaths=[]
 for(const [name,body]of outputs){
  if(path.isAbsolute(name)||name.split(/[\\/]/).includes('..'))throw Error('Invalid output path')
  const target=path.join(directory,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,body);outputPaths.push(name)
 }
 function copy(from,to,accept=()=>true){for(const name of files(from)){if(!accept(name))continue;const target=path.join(to,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(path.join(from,name),target)}}
 copy(path.join(shared,'img'),path.join(directory,'public/img/shared'))
 copy(path.join(shared,'admin'),path.join(directory,'public/admin'))
 const cmsBranch=process.env.DOCS_CMS_BRANCH
 if(cmsBranch){
  if(!/^[A-Za-z0-9._/-]+$/.test(cmsBranch)||cmsBranch.includes('..'))throw Error('Invalid CMS branch')
  const config=path.join(directory,'public/admin/config.yml')
  if(fs.existsSync(config))fs.writeFileSync(config,fs.readFileSync(config,'utf8').replace(/^  branch:.*$/m,'  branch: '+cmsBranch))
 }
 copy(path.join(path.dirname(root),'assets'),path.join(directory,'public/img/course'),name=>/\.(png|jpe?g|webp|svg|css)$/i.test(name))
 console.log(JSON.stringify({site:id,generated:outputPaths.length,courseChapters:course.sources.filter(x=>x.id.startsWith('ch')).length,sourceVersion:course.version}))
 return outputPaths
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 try{build(process.argv[2])}catch(error){console.error(error.message);process.exitCode=1}
}
