import type {Theme} from 'vitepress'
import StudioLayout from './StudioLayout.vue'
import StudioChapter from './StudioChapter.vue'
import StudioHub from './StudioHub.vue'
import SkillWorkshop from './SkillWorkshop.vue'
import IndustryLesson from './IndustryLesson.vue'
import ScreenshotCatalog from './ScreenshotCatalog.vue'
import ScreenshotSlot from './ScreenshotSlot.vue'
import SupportPanel from './SupportPanel.vue'
import DownloadCards from '../../shared/theme/DownloadCards.vue'
import './studio.css'
export default {Layout:StudioLayout,enhanceApp({app}){for(const [name,component]of Object.entries({StudioChapter,StudioHub,SkillWorkshop,IndustryLesson,ScreenshotCatalog,ScreenshotSlot,SupportCard:SupportPanel,DownloadCards}))app.component(name,component)}} satisfies Theme
