import {download} from './shot-store.js'
import css from './studio.css?raw'
import clarity from './clarity.css?raw'
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
function offlineApp(){const state=JSON.parse(document.getElementById('offline-state').textContent),specs=new Map(state.manifest.map(s=>[s.id,s])),records=state.snapshot.records;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const save=(name,text,type)=>{const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)};
 function draw(){for(const host of document.querySelectorAll('[data-shot-id]')){const id=host.dataset.shotId,s=specs.get(id)||{title:'步骤截图'},r=records[id]||{images:[]};if((r.hidden||(!r.images.length&&state.snapshot.hideMissing))&&!state.editable){host.innerHTML='';continue}host.innerHTML='<div class="shot-frame"><div class="shot-top"><strong>'+esc(s.title)+'</strong><small>'+id+'</small></div>'+(r.hidden?'<p>此位置已隐藏</p>':r.images.length?r.images.map((im,i)=>'<figure class="shot-image"><img src="'+esc(im.data)+'" alt="'+esc(r.alt||s.title)+'"><figcaption>'+esc(r.caption||s.title)+'</figcaption>'+(state.editable?'<button data-remove="'+id+'" data-index="'+i+'">移除此图</button>':'')+'</figure>').join(''):'<div class="shot-empty">▧ 待补充真实截图</div>')+(state.editable?'<div class="shot-editor"><p>'+esc(r.target||s.target||'拍摄实际步骤，先遮盖敏感信息')+'</p><input data-add="'+id+'" type="file" accept="image/png,image/jpeg,image/webp" multiple><button data-meta="'+id+'">编辑图注</button><button data-hide="'+id+'">'+(r.hidden?'恢复显示':'隐藏此位置')+'</button></div>':'')+'</div>'}}
 document.addEventListener('click',e=>{const n=e.target.closest('button');if(!n)return;if(n.dataset.copy!==undefined){navigator.clipboard?.writeText(n.dataset.copy);return}if(n.id==='save-json')save('screenshots-'+state.snapshot.siteId+'-v5.4.json',JSON.stringify(state.snapshot,null,2),'application/json');if(n.id==='save-html'){document.getElementById('offline-state').textContent=JSON.stringify(state).replace(/</g,'\\u003c');save('course-'+state.snapshot.siteId+'-v5.4-'+(state.editable?'editable':'reading')+'.html','<!doctype html>\n'+document.documentElement.outerHTML,'text/html')}
 if(!state.editable)return;const id=n.dataset.remove||n.dataset.meta||n.dataset.hide;if(!id)return;records[id]||={images:[]};if(n.dataset.remove)records[id].images.splice(Number(n.dataset.index),1);if(n.dataset.hide)records[id].hidden=!records[id].hidden;if(n.dataset.meta){const text=prompt('图注（取消不会修改）',records[id].caption||'');if(text!==null)records[id].caption=text.slice(0,3000)}draw()});
 document.addEventListener('change',async e=>{const id=e.target.dataset.add;if(!state.editable||!id)return;const files=[...e.target.files],old=records[id]||{images:[]};try{if(old.images.length+files.length>6)throw Error('每个位置最多6张');const images=[];for(const f of files){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>12*1024*1024)throw Error('仅支持12MB以内的PNG/JPG/WebP');const data=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});const size=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok([i.naturalWidth,i.naturalHeight]);i.onerror=no;i.src=data});if(size[0]*size[1]>32e6)throw Error('图像像素过大');images.push({data,name:f.name,width:size[0],height:size[1]})}records[id]={...old,images:[...old.images,...images]};draw()}catch(err){alert(err.message)}e.target.value=''});draw()}
export async function exportCourseHTML(api,role){const snapshot=api.snapshot();for(const r of Object.values(snapshot.records))for(const im of r.images||[]){if(im.data.startsWith('/screenshots/')){const response=await fetch(im.data,{credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)throw Error('读取已发布截图失败，未导出不完整文件');const blob=await response.blob();im.data=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(blob)})}}
 const data=api.data;const urlBody=(html,ch)=>html.replace(/href="#(s\d+)"/g,(_,s)=>'href="#'+ch+'-'+s+'"').replace(/href="\/learn\/codex\/(ch\d+)(?:#(s\d+))?"/g,(_,c,s)=>'href="#'+c+(s?'-'+s:'')+'"').replace(/href="\/(?!\/)([^"]*)"/g,(_,p)=>'href="https://'+data.site.domain+'/'+p+'"');
 const content=data.chapters.map(ch=>'<article class="studio-lesson" id="'+ch.id+'"><p class="eyebrow">第 '+ch.n+' 章</p><h1>'+esc(ch.title)+'</h1>'+(ch.lead?'<p class="lead">'+esc(ch.lead)+'</p>':'')+ch.sections.map(s=>'<section class="course-section" id="'+ch.id+'-'+s.anchor+'"><h2>'+esc(s.title)+'</h2><div class="yichen-article">'+urlBody(s.body,ch.id)+'</div></section>').join('')+'</article>').join('');
 const state={editable:role==='editor',snapshot,manifest:data.manifest};const clarityCss=typeof clarity==='string'?clarity:'';const html='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>星芒 Codex 课程 v5.4</title><style>'+css+'\n'+clarityCss+'\n.studio-lesson{margin-bottom:90px}.studio-top{height:auto;min-height:64px;flex-wrap:wrap}.studio-body{padding-top:100px}.offline-nav{overflow:auto;max-height:80vh}.offline-course .course-section>table{display:block;max-width:100%;overflow-x:auto}</style></head><body><div class="studio-shell offline-course"><aside class="studio-rail"><a class="studio-brand" href="#ch01">✦ 星芒 AI</a><nav class="offline-nav">'+data.chapters.map(c=>'<a href="#'+c.id+'">'+c.n+'. '+esc(c.title)+'</a>').join('')+'</nav></aside><header class="studio-top"><strong>27 章图文教程 · v5.4 · '+(state.editable?'补图编辑':'阅读版')+'</strong><button id="save-html">保存当前 HTML</button>'+(state.editable?'<button id="save-json">截图 JSON 备份</button>':'')+'<small>工具接入、FAQ 等链接仍前往本站文档；此文件不发布网站。</small></header><div class="studio-body"><main id="studio-main">'+content+'</main></div></div><script type="application/json" id="offline-state">'+JSON.stringify(state).replace(/</g,'\\u003c')+'</script><script>('+offlineApp.toString()+')()</script></body></html>';download('course-'+data.site.id+'-v5.4-'+role+'.html',html,'text/html;charset=utf-8')}
