import {reactive,provide,inject,onMounted,onBeforeUnmount} from 'vue'
import {SCHEMA,parseSnapshot,safeRecord} from './shot-schema.mjs'
export const SHOTS=Symbol('xingmang-local-shots')
export function download(name,content,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
export function installShots(raw){const data=JSON.parse(JSON.stringify(raw)),specs=new Map(data.manifest.map(x=>[x.id,x]));const state=reactive({editing:false,active:'',records:data.shots.records||{},hideMissing:!!data.shots.hideMissing,dirty:false,message:'',cache:null,unknown:[],busy:false});let db=null,timer;const say=m=>{state.message=m;clearTimeout(timer);timer=setTimeout(()=>state.message='',6500)};const snapshot=()=>({schema:SCHEMA,version:'5.3',siteId:data.site.id,updatedAt:Date.now(),hideMissing:state.hideMissing,records:JSON.parse(JSON.stringify(state.records))});
 function persist(){if(!db)return;try{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(snapshot(),data.site.id);tx.onabort=()=>say('本机缓存失败，请导出 JSON 备份。')}catch{say('缓存不可用，请导出备份。')}}
 function update(id,record){state.records[id]=safeRecord(record);state.dirty=true;persist()}
 function exportJSON(current=false){const s=snapshot();if(current){const ids=new Set([...document.querySelectorAll('[data-shot-id]')].map(n=>n.dataset.shotId));s.records=Object.fromEntries(Object.entries(s.records).filter(([id])=>ids.has(id)))}download('screenshots-'+data.site.id+(current?'-chapter':'')+'-v5.3.json',JSON.stringify(s,null,2));if(!current)state.dirty=false;say('已导出到本机；GitHub 和线上教程没有改变。')}
 async function importJSON(file,shared=false){if(!file)return;if(file.size>150*1024*1024)throw Error('备份超过150MB，请按章节拆分后导入');const r=parseSnapshot(JSON.parse(await file.text()),data.site.id,specs,shared);state.records={...state.records,...r.records};state.unknown=r.unknown;state.hideMissing=r.hideMissing;state.dirty=true;persist();say('已导入 '+Object.keys(r.records).length+' 个位置；'+r.unknown.length+' 个暂未匹配，仍保留在备份中；跳过 '+r.skipped.length+' 个不允许跨站复用的位置。')}
 function restore(){if(!state.cache)return;try{const r=parseSnapshot(state.cache,data.site.id,specs);state.records={...state.records,...r.records};state.hideMissing=r.hideMissing;state.unknown=r.unknown;state.cache=null;state.dirty=true;say('本机草稿已恢复，请导出文件备份。')}catch(e){say(e.message)}}
 async function upload(id,files,replace=-1){if(!state.editing||state.busy)return;const old=state.records[id]||{images:[]};const incoming=[...files];if(!incoming.length)return;if(replace<0&&old.images.length+incoming.length>6)throw Error('每个图片位最多6张');state.busy=true;try{const next=[];for(const f of incoming){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>12*1024*1024)throw Error('每张截图限12MB，只支持 PNG、JPG、WebP');const src=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=()=>no(Error('读取失败'));r.readAsDataURL(f)});const dim=await new Promise((ok,no)=>{const image=new Image();image.onload=()=>ok([image.naturalWidth,image.naturalHeight]);image.onerror=()=>no(Error('图片不能解码'));image.src=src});if(dim[0]*dim[1]>32e6)throw Error('截图超过3200万像素');next.push({data:src,name:f.name||'剪贴板截图',width:dim[0],height:dim[1]})}const r=JSON.parse(JSON.stringify(old));if(replace>=0){if(!r.images[replace])throw Error('原图已不存在');r.images.splice(replace,1,next[0])}else r.images.push(...next);update(id,r);say('截图已读取到本机；没有上传服务器。请导出备份。')}finally{state.busy=false}}
 const before=e=>{if(state.dirty){e.preventDefault();e.returnValue=''}};const paste=e=>{if(!state.editing||!state.active||/INPUT|TEXTAREA/.test(e.target?.tagName))return;const files=[...(e.clipboardData?.files||[])];if(files.length){e.preventDefault();upload(state.active,files).catch(e=>say(e.message))}};
 onMounted(()=>{state.editing=new URLSearchParams(location.search).get('edit')==='1';window.addEventListener('beforeunload',before);window.addEventListener('paste',paste);try{const req=indexedDB.open('xingmang-studio-v53',1);req.onupgradeneeded=()=>req.result.createObjectStore('drafts');req.onsuccess=()=>{db=req.result;const get=db.transaction('drafts').objectStore('drafts').get(data.site.id);get.onsuccess=()=>{if(get.result)state.cache=get.result}};req.onerror=()=>say('当前环境不能缓存，请导出备份。')}catch{say('当前环境不能缓存，请导出备份。')}});
 onBeforeUnmount(()=>{clearTimeout(timer);window.removeEventListener('beforeunload',before);window.removeEventListener('paste',paste);db?.close()});const api={state,specs,data,snapshot,update,exportJSON,importJSON,restore,upload,say};provide(SHOTS,api);return api
}
export function useShots(){const store=inject(SHOTS);if(!store)throw Error('Screenshot store is not mounted');return store}
