<script setup>
import {ref,computed} from 'vue'
import {useData} from 'vitepress'
import {download} from './shot-store.js'
import ScreenshotSlot from './ScreenshotSlot.vue'
const {theme}=useData(),tab=ref('build'),initial=theme.value.studio.chapters.find(c=>c.id==='ch07').sections.find(s=>s.title.startsWith('手工创建'))?.body||''
const decode=s=>s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&')
const source=ref(decode(initial.match(/<pre>([\s\S]*?)<\/pre>/)?.[1]||'---\nname: my-skill\ndescription: 说明什么时候使用这个技能。\n---\n\n# 技能说明\n'))
const checks=computed(()=>[['有 YAML 前置信息',/^---\r?\n[\s\S]*?\r?\n---/.test(source.value)],['名称明确',/^name:\s*\S+/m.test(source.value)],['描述不为空',/^description:\s*\S+/m.test(source.value)],['有操作正文',source.value.replace(/^---[\s\S]*?---/,'').trim().length>30]])
</script>
<template><article class="studio-lesson"><a href="/learn/codex/ch07" class="crumb">← 第 7 章 · Skill 全过程</a><p class="eyebrow">SKILL / BUILD · INSTALL · VERIFY</p><h1>把做顺的任务，<br>留成可复用的方法。</h1><p class="lead">从一份纯指令 SKILL.md 开始。这里不运行代码、不安装技能、不调用模型。</p><div class="filter-bar"><button v-for="[id,label] in [['build','制作技能'],['install','安装与调用'],['test','测试与改进']]" :key="id" :class="{active:tab===id}" @click="tab=id">{{label}}</button></div>
<section v-show="tab==='build'"><h2>先读规则，再修改自己的版本</h2><div class="workshop-grid"><div><label for="skill-source">SKILL.md</label><textarea id="skill-source" class="skill-source" v-model="source" spellcheck="false"></textarea><button class="gold-button" @click="download('SKILL.md',source,'text/markdown;charset=utf-8')">保存 SKILL.md ↓</button></div><aside class="workshop-checks"><h3>基础格式检查</h3><p v-for="[label,ok] in checks" :key="label">{{ok?'✓':'○'}} {{label}}</p><p>这里只检查字段和基本结构，不是完整 YAML 校验，也不证明技能能实际完成任务。</p><pre>.agents/skills/\n└── 技能目录/\n    └── SKILL.md</pre></aside></div><ScreenshotSlot slot-id="skills-editor" /></section>
<section v-show="tab==='install'"><h2>保存文件，不等于已经安装</h2><ol class="numbered-guide"><li>检查技能来源、内容和依赖。样例不需要脚本或外部账号。</li><li>按实际产品确认项目范围与个人范围，不混用桌面界面和终端路径。</li><li>把文件放入正确的技能目录，检查不是 SKILL.md.txt，也没有多套一层文件夹。</li><li>刷新或重新打开当前产品，确认技能被发现，再显式调用。</li><li>输入虚构材料并检查实际结果；不能把“出现在列表”当作测试通过。</li></ol><ScreenshotSlot slot-id="skills-install" /><p class="edu-note">实际安装步骤以第7章及其注明的产品条件为准。浏览器保存文件不会写入你的技能目录。</p></section>
<section v-show="tab==='test'"><h2>不要只测试一次</h2><div class="path-grid"><article v-for="[title,input,result] in [['正常','10 本＋8 本＋12 本，同一产品与周期','应为30本，不猜销售额。'],['缺失','周一10本，周二数量空白','标记缺失，不把空白当0。'],['冲突','同一天一份记录8本，另一份80本','先询问，不擅自选择或求平均。']]" :key="title" class="path-card"><h3>{{title}}</h3><p>{{input}}</p><strong>{{result}}</strong></article></div><ScreenshotSlot slot-id="skills-test" /><p>这些是作者编写的验收标准，不是一次实际模型调用。将实际结果和版本记录在自己的测试笔记中。</p></section></article></template>
