<script setup>
import {computed,ref,onMounted,onBeforeUnmount,nextTick,watch} from 'vue'
import {Content,useData,useRoute} from 'vitepress'
import {installShots} from './shot-store.js'
import StudioHub from './StudioHub.vue'
import SupportPanel from './SupportPanel.vue'
import ScreenshotSlot from './ScreenshotSlot.vue'
import EditorBar from './EditorBar.vue'
const {theme}=useData(),route=useRoute(),data=computed(()=>theme.value.studio),api=installShots(data.value),menu=ref(false),focus=ref(false),search=ref(''),searchDialog=ref(),main=ref(),targets=ref([]),errorQuery=ref('');const current=computed(()=>route.path.replace(/\.html$/,'').replace(/\/$/,'')||'/');const isHome=computed(()=>current.value==='/'||current.value==='/guide/start');const isHelp=computed(()=>['/errors','/faq'].includes(current.value));const chapterId=computed(()=>current.value.match(/\/learn\/codex\/(ch\d+)/)?.[1]);
const nav=computed(()=>[['⌂','教程总览','/guide/start'],['▣','Codex 零基础','/learn/codex/'],['◇','工具接入','/tools'],['▤','Skill 工坊','/skills'],['▧','行业实战','/industry/'],['▱','管理工具','/guide/manager'],['◷',data.value.site.id==='sub2api'?'订阅与额度':'充值与用量','/guide/account'],['?','常见问题','/faq'],['!','错误码对照','/errors'],['◎','联系客服','/contact']]);
const results=computed(()=>{const q=search.value.trim().toLowerCase();if(!q)return[];const list=[...data.value.chapters.flatMap(c=>c.sections.map((s,i)=>({title:c.n+'.'+(i+1)+' '+s.title,route:'/learn/codex/'+c.id+'#'+s.anchor,text:s.body.replace(/<[^>]*>/g,' ')}))),...data.value.docs];return list.filter(x=>(x.title+' '+x.text).toLowerCase().includes(q)).slice(0,35)});
function openSearch(){searchDialog.value.showModal();nextTick(()=>searchDialog.value.querySelector('input').focus())}
function keyboard(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}}
async function copy(e){const button=e.target.closest('[data-copy]');if(!button)return;try{await navigator.clipboard.writeText(button.dataset.copy);api.say('已复制；未发送请求。')}catch{api.say('当前环境不能直接复制，请手动选择文本。')}}
async function pageReady(){menu.value=false;errorQuery.value='';targets.value=[];await nextTick();if(chapterId.value||isHome.value||current.value.startsWith('/industry')||['/skills','/screenshots'].includes(current.value))return;const specs=data.value.manifest.filter(s=>s.route===current.value);const items=[...(main.value?.querySelectorAll('.vp-doc ol > li')||[])].filter(li=>!li.parentElement.closest('li'));const found=[];items.forEach((li,i)=>{if(!specs[i])return;let host=li.querySelector(':scope > .legacy-shot');if(!host){host=document.createElement('div');host.className='legacy-shot';host.dataset.shotId=specs[i].id;li.append(host)}found.push({id:specs[i].id,host})});targets.value=found}
function filterHelp(){const q=errorQuery.value.trim().toLowerCase();main.value?.querySelectorAll('.vp-doc tbody tr').forEach(tr=>tr.hidden=!!q&&!tr.textContent.toLowerCase().includes(q));if(current.value==='/faq'){const heads=[...(main.value?.querySelectorAll('.vp-doc h2')||[])];for(const h of heads){let nodes=[h],n=h.nextElementSibling;while(n&&n.tagName!=='H2'){nodes.push(n);n=n.nextElementSibling}const hidden=!!q&&!nodes.map(n=>n.textContent).join(' ').toLowerCase().includes(q);nodes.forEach(n=>n.hidden=hidden)}}}
watch(()=>route.path,pageReady,{flush:'post'});watch(errorQuery,filterHelp);onMounted(()=>{window.addEventListener('keydown',keyboard);pageReady()});onBeforeUnmount(()=>window.removeEventListener('keydown',keyboard));
</script>
<template><div class="studio-shell" :class="{'menu-open':menu,'focus-mode':focus}"><a class="skip" href="#studio-main">跳到正文</a><button v-if="menu" class="rail-scrim" @click="menu=false" aria-label="关闭目录"></button><aside class="studio-rail"><a class="studio-brand" href="/guide/start"><span class="brand-star">✦</span><span>星芒 AI<small>LEARNING SPACE</small></span></a><nav aria-label="学习中心"><a v-for="[icon,label,href] in nav" :key="href" :href="href" :class="{active:href==='/learn/codex/'?current.startsWith('/learn/codex'):current===href.replace(/\/$/,'')}" :aria-current="current===href?'page':undefined"><span aria-hidden="true">{{icon}}</span>{{label}}<small v-if="href==='/learn/codex/'">11</small></a></nav><SupportPanel /><a class="rail-edit" href="/screenshots">截图工作台 · 本机编辑</a></aside><header class="studio-top"><button class="menu-toggle" @click="menu=!menu" :aria-expanded="menu" aria-label="展开目录">☰</button><span class="top-crumb">星芒文档 <b>/ 学习中心</b></span><div class="top-actions"><span class="version-tag">v5.3</span><button class="search-trigger" @click="openSearch">⌕ 搜索教程、工具与问题 <kbd>Ctrl K</kbd></button><a :href="data.site.console_url" target="_top" rel="noreferrer">返回控制台 ↗</a><button class="focus-button" @click="focus=!focus">{{focus?'退出专注':'专注阅读'}}</button></div></header><div class="studio-body"><EditorBar /><main ref="main" id="studio-main" tabindex="-1" @click="copy"><StudioHub v-if="isHome" kind="home"/><template v-else><div v-if="isHelp" class="help-search"><label>按{{current==='/errors'?'错误原文':'问题关键词'}}查找<input v-model="errorQuery" placeholder="例如 429、余额、模型、充值" /></label><p>旧版本站内容原样保留。状态码不等于唯一原因；涉及版本、接口路径和计费规则时核对当前本站记录。</p></div><Content :key="route.path" class="vp-doc" /></template><Teleport v-for="target in targets" :key="target.id" :to="target.host"><ScreenshotSlot :slot-id="target.id"/></Teleport><footer class="studio-footer"><span>星芒 AI 学习空间 · 少一些摸索，多一些开始。</span><a href="/contact">需要帮助</a><span>v5.3 · 课程与实际版本请分别核对</span></footer></main></div><aside v-if="chapterId&&!focus" class="reading-toc"><small>本章路线</small><a v-for="(s,i) in data.chapters.find(c=>c.id===chapterId).sections" :key="s.anchor" :href="'#'+s.anchor">{{i+1}}. {{s.title}}</a><a href="#practice">动手练习与检查</a></aside><div v-if="api.state.message" class="studio-toast" role="status">{{api.state.message}}</div><dialog ref="searchDialog" class="search-dialog"><div class="dialog-head"><strong>在本站教程中搜索</strong><button @click="searchDialog.close()">关闭 ×</button></div><input v-model="search" placeholder="搜索课程、Skill 或报错文案" aria-label="搜索"><div class="search-results"><a v-for="r in results" :key="r.route" :href="r.route" @click="searchDialog.close()">{{r.title}}<small>{{r.text.slice(0,100)}}</small></a><p v-if="search&&!results.length">没有结果，请换一个关键词。</p></div></dialog></div></template>
